# Generated by Django 2.1.8 on 2019-04-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_auto_20190408_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
