# Generated by Django 2.0 on 2019-04-12 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onetime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
